.gitignore
.vscode/launch.json
quasar.conf.js
src/pages/home/LoginSelect.vue

Debug directly from VSCode. Follows https://quasar.dev/start/vs-code-configuration#Debugging-a-Quasar-project-in-VS-Code

Vscode debug

---

.gitignore
src/components/GroupCard.vue
src/components/SelectLang.vue
src/i18n/ca/index.ts
src/i18n/en-us/index.ts
src/i18n/es/index.ts
src/layouts/Front.vue
src/pages/groups/GroupList.vue
src/pages/home/Login.vue
src/pages/home/LoginMail.vue
src/pages/home/LoginSelect.vue

Hi, this is about #54 
Please, review.

I18n keys and strings

---

Dockerfile
src/components/GroupCard.vue
src/components/GroupStats.vue
src/components/SimpleMap.vue
src/plugins/CardClickTo.ts

About https://github.com/komunitin/komunitin/issues/47

Cards clickable

---

src/layouts/Layout.vue
src/pages/groups/Group.vue

Menu button for default layout

---

src/components/MenuDrawer.vue
src/components/MenuItem.vue
src/pages/groups/Group.vue
src/pages/groups/GroupList.vue

And fixed bug with group to group navigation.

"Other groups" menu item

---

src/KError.ts
src/pages/offers/OfferList.vue
src/server/ApiSerializer.ts
src/store/resources.ts
test/jest/__tests__/Offers.spec.ts

Adds pagination and infinite scroll to offers page

Offers scroll

---

src/pages/ResourceCardList.vue
src/pages/offers/OfferList.vue

So the implementation can be shared among other card lists, such as groups list or needs list.

Make OfferList generic

---

src/components/MenuDrawer.vue
src/server/AccountingServer.ts
src/store/index.ts
src/store/me.ts
src/store/model.ts
src/store/resources.ts
test/jest/__tests__/LoggedIn.spec.ts

- link it to current user
- display on menu drawer

Add account resource

---

src/pages/transactions/TransactionList.vue
src/server/AccountingServer.ts
src/store/index.ts
src/store/model.ts
test/jest/__tests__/Transactions.spec.ts

Merge transactions into transfers

---

src/boot/errors.ts
src/css/app.sass
src/css/quasar.variables.sass
src/i18n/ca/index.json
src/i18n/en-us/index.json
src/i18n/es/index.json
src/layouts/PageHeader.vue
src/layouts/__tests__/PageHeader.spec.ts
src/pages/ResourceCardList.vue
src/pages/groups/Group.vue

Prominent bar

---

src/components/NeedCard.vue
src/components/OfferCard.vue
src/css/app.sass
src/server/SocialServer.ts
src/store/model.ts
test/jest/__tests__/Needs.spec.ts
test/jest/__tests__/Offers.spec.ts

Category icons

---

src/components/Carousel.vue
src/components/CategoryAvatar.vue
src/components/NeedCard.vue
src/components/OfferCard.vue
src/debug.log
src/i18n/ca/index.json
src/i18n/en-us/index.json
src/i18n/es/index.json
src/layouts/OfferLayout.vue
src/pages/needs/Need.vue
src/pages/offers/Offer.vue
src/router/routes.ts
src/server/SocialServer.ts
test/jest/__tests__/Needs.spec.ts

Need detail, offer layout refactored

---

src/boot/auth.ts
src/components/MenuDrawer.vue
src/components/MenuItem.vue
src/i18n/ca/index.json
src/i18n/en-us/index.json
src/i18n/es/index.json
src/pages/home/Login.vue
src/pages/home/LoginMail.vue
src/pages/transactions/Transaction.vue
src/pages/transactions/TransactionItems.vue
test/jest/__tests__/LoggedIn.spec.ts
test/jest/__tests__/Login.spec.ts
test/jest/__tests__/Members.spec.ts
test/jest/__tests__/Needs.spec.ts
test/jest/__tests__/Offers.spec.ts
test/jest/__tests__/Transactions.spec.ts

- Hide social login (didnt work yet)
- Hide home menu item (didnt work yet)
- Minor issues
- Route guards to private routes
- Login redirection

Version 0.1

---

package-lock.json
package.json
src/components/Avatar.vue
src/components/Carousel.vue
src/components/CategoryAvatar.vue
src/components/FitText.vue
src/components/GroupCard.vue
src/components/MemberHeader.vue
src/components/MenuDrawer.vue
src/components/NeedCard.vue
src/components/OfferCard.vue
src/components/__tests__/Avatar.spec.ts
src/debug.log
src/pages/members/MemberPageHeader.vue
src/pages/needs/Need.vue
src/pages/offers/Offer.vue
src/server/SocialServer.ts
test/jest/__tests__/Members.spec.ts
tsconfig.json

Default avatar for members

---

app/src/pages/transactions/ConfirmCreateTransaction.vue
app/src/plugins/Notifications.ts
app/src/plugins/NotifyTransactionState.ts
notifications/docker-compose.yml

Minimal foreground notifications

Notifications2

---

.env.template
compose.dev.yml

Fix dev build with docker compose

---

.gitignore
app/src/components/PasswordField.vue
app/src/pages/home/ForgotPassword.vue
app/src/pages/members/Member.vue
app/src/pages/offers/Offer.vue
app/src/router/routes.ts
app/test/jest/__tests__/Member.spec.ts
notifications/mails/templates.go

Fixes bugs #384 #371 #385 and #375

---

accounting/src/controller/account-controller.ts
accounting/src/ledger/ledger.ts
accounting/src/ledger/stellar/account.ts
accounting/src/ledger/stellar/currency.ts
accounting/test/server/2.account.api.test.ts

Fixes Arbitrarily large credit limit #370

---

accounting/src/controller/account-controller.ts
accounting/src/controller/currency-controller.ts
accounting/src/controller/external-transfer-controller.ts
accounting/src/controller/features/credit-on-payment.ts
accounting/src/controller/features/notificatons.ts
accounting/src/controller/index.ts
accounting/src/controller/migration/integralces.ts
accounting/src/controller/transfer-controller.ts
accounting/src/controller/user-controller.ts
accounting/src/model/account.ts
accounting/src/model/currency.ts
accounting/src/model/transfer.ts
accounting/src/server/routes.ts
accounting/src/server/serialize.ts
accounting/src/server/validation.ts
accounting/test/server/1.currency.api.test.ts
accounting/test/server/13.account.settings.api.test.ts
accounting/test/server/2.account.api.test.ts
app/src/composables/currencySettings.ts
app/src/i18n/ca/admin.json
app/src/i18n/en-us/admin.json
app/src/i18n/es/admin.json
app/src/i18n/it/admin.json
app/src/pages/members/MemberList.vue
app/src/pages/members/MemberPageHeader.vue
app/src/pages/settings/AccountSettingsFields.vue
app/src/store/model.ts

Hide balances setting

---

accounting/README.md
accounting/cc/Dockerfile
accounting/src/creditcommons/credit-commons-controller.ts
compose.yml
start.sh

This is a PR on top of #405, with the main goal of implementing [this TODO](https://github.com/community-exchange-network/komunitin/pull/405/files#diff-e71273ea74983d9ae8d3a0f4fb4dbb1d5b0dbe51dda2e117dc25372a50400b60R422-R425)

Connecting QR with CreditCommons

---

accounting/src/controller/account-controller.ts
accounting/test/server/10.tag.transfer.api.test.ts

Fix bug with tags

---

app/src/layouts/Layout.vue
app/src/store/ui.ts

Fixes https://github.com/community-exchange-network/ces2/issues/97

97 Add bottom nav-bar
